// Generated by CoffeeScript 1.6.3

var gulp   = require('gulp');
var coffee = require('gulp-coffee');
var filter = require('gulp-filter');
var mocha  = require('gulp-mocha');
var gutil  = require('gulp-util');

var src = ['*.coffee'];

// otherwise mocha with throw a fit
require('coffee-script/register');

gulp.task('watch', ['default'], function() {
  gulp.watch(src, ['default']);
});

gulp.task('default', function() {
  var outFilter = filter('index.coffee');
  gulp.src(src)
    .pipe(outFilter)
    .pipe(coffee({bare: true}).on('error', gutil.log))
    .pipe(gulp.dest('.'))
    .pipe(outFilter.restore())
    .pipe(mocha({reporter: 'nyan'}))
    .on("error", function(err) {
      gutil.log(err.toString());
      this.emit('end');
    });
});
